[2023-04-25T08:43:20.911+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: database_processing.insert_into_table manual__2023-04-25T08:43:18.878880+00:00 [queued]>
[2023-04-25T08:43:20.917+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: database_processing.insert_into_table manual__2023-04-25T08:43:18.878880+00:00 [queued]>
[2023-04-25T08:43:20.918+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T08:43:20.918+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-04-25T08:43:20.919+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-04-25T08:43:20.926+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2023-04-25 08:43:18.878880+00:00
[2023-04-25T08:43:20.931+0000] {standard_task_runner.py:55} INFO - Started process 9894 to run task
[2023-04-25T08:43:20.934+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'database_processing', 'insert_into_table', 'manual__2023-04-25T08:43:18.878880+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/database_processing.py', '--cfg-path', '/tmp/tmpd__lt13t']
[2023-04-25T08:43:20.935+0000] {standard_task_runner.py:83} INFO - Job 18: Subtask insert_into_table
[2023-04-25T08:43:20.985+0000] {task_command.py:388} INFO - Running <TaskInstance: database_processing.insert_into_table manual__2023-04-25T08:43:18.878880+00:00 [running]> on host 2f9666fcabde
[2023-04-25T08:43:21.030+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=database_processing
AIRFLOW_CTX_TASK_ID=insert_into_table
AIRFLOW_CTX_EXECUTION_DATE=2023-04-25T08:43:18.878880+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-25T08:43:18.878880+00:00
[2023-04-25T08:43:21.031+0000] {sql.py:254} INFO - Executing: 
            INSERT INTO USERS(id,name,email,phone,address,organization) VALUES
            (2,'shubham','rshuh@gmail.com','+917938535736','hyderabad','amazon'),
            (3,'pankaj','pankajksh@gmail.com','+917838895736','bihar','apple'),
            (4,'raj','rajkumar@gmail.com','+916783456890','ranchi','aidash');
        
[2023-04-25T08:43:21.039+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-04-25T08:43:21.137+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-04-25T08:43:21.142+0000] {sql.py:375} INFO - Running statement: 
            INSERT INTO USERS(id,name,email,phone,address,organization) VALUES
            (2,'shubham','rshuh@gmail.com','+917938535736','hyderabad','amazon'),
            (3,'pankaj','pankajksh@gmail.com','+917838895736','bihar','apple'),
            (4,'raj','rajkumar@gmail.com','+916783456890','ranchi','aidash');
        , parameters: None
[2023-04-25T08:43:21.144+0000] {sql.py:384} INFO - Rows affected: 3
[2023-04-25T08:43:21.153+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=database_processing, task_id=insert_into_table, execution_date=20230425T084318, start_date=20230425T084320, end_date=20230425T084321
[2023-04-25T08:43:21.193+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-04-25T08:43:21.210+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
